import React, { useState, useEffect, useMemo } from 'react';
import { useNavigate, useParams, Link } from 'react-router-dom';
import api from '../api';
import { FiArrowLeft, FiPlus, FiX, FiSave, FiPackage, FiTag, FiCopy, FiCheck, FiLayers, FiTrash2 } from 'react-icons/fi';
import { useSettings } from '../contexts/SettingsContext';
import './AddProduct.css';

/**
 * Generate sorting code from product details:
 * - First letter of first two words of brand name
 * - First letter of each word in product name
 * - First number from volume/size (or first 2 numbers if volume >= 1000)
 * 
 * Example: "Dr Vranjes" + "Rosso Nobile Diffuser" + "500ml" = "DVRND5"
 * Example: "Dr Vranjes" + "Rosso Nobile Diffuser" + "2000ml" = "DVRND20"
 */
const generateSortingCode = (brandName, productName, volumeSize) => {
  if (!brandName || !productName) return '';

  // Get first letter of first two words of brand name
  const brandWords = brandName.trim().split(/\s+/).filter(Boolean);
  const brandInitials = brandWords
    .slice(0, 2)
    .map(word => word.charAt(0).toUpperCase())
    .join('');

  // Get first letter of each word in product name
  const productWords = productName.trim().split(/\s+/).filter(Boolean);
  const productInitials = productWords
    .map(word => word.charAt(0).toUpperCase())
    .join('');

  // Get digits from volume/size
  const volumeNumberMatch = (volumeSize || '').match(/\d+/);
  let volumeDigits = '';
  if (volumeNumberMatch) {
    const volumeNumber = parseInt(volumeNumberMatch[0], 10);
    // If volume >= 1000, use first 2 digits; otherwise use first digit
    volumeDigits = volumeNumber >= 1000 
      ? volumeNumberMatch[0].slice(0, 2) 
      : volumeNumberMatch[0].charAt(0);
  }

  return `${brandInitials}${productInitials}${volumeDigits}`;
};

/**
 * Generate full display name from components
 */
const generateDisplayName = (brandName, productName, volumeSize) => {
  const parts = [brandName, productName, volumeSize].filter(Boolean);
  return parts.join(' - ');
};

const AddProduct = () => {
  const navigate = useNavigate();
  const { id } = useParams();
  const isEditing = Boolean(id);
  const { currencySymbol, formatCurrency } = useSettings();

  // Mode: 'single' or 'bulk'
  const [mode, setMode] = useState('single');

  const [formData, setFormData] = useState({
    brand_name: '',
    product_name: '',
    volume_size: '',
    sorting_code: '',
    description: '',
    cost_of_production: '',
    markup_percentage: '',
    markup_amount: '',
    stock_quantity: ''
  });
  const [lineItems, setLineItems] = useState([]);
  const [newLineItem, setNewLineItem] = useState({ item_name: '', cost: '' });
  const [loading, setLoading] = useState(false);
  const [pricingError, setPricingError] = useState('');
  const [codeCopied, setCodeCopied] = useState(false);
  const [manualCodeEdit, setManualCodeEdit] = useState(false);

  // Bulk mode state
  const [bulkBrandName, setBulkBrandName] = useState('');
  const [bulkProducts, setBulkProducts] = useState([]);
  const [bulkDefaults, setBulkDefaults] = useState({
    cost_of_production: '',
    markup_percentage: '',
    markup_amount: '',
    stock_quantity: ''
  });
  const [newBulkProduct, setNewBulkProduct] = useState({
    product_name: '',
    volume_size: '',
    description: '',
    cost_of_production: '',
    markup_percentage: '',
    markup_amount: '',
    stock_quantity: ''
  });
  const [useDefaults, setUseDefaults] = useState(true);

  // Auto-generate sorting code when brand, product name, or volume changes
  const autoGeneratedCode = useMemo(() => {
    return generateSortingCode(formData.brand_name, formData.product_name, formData.volume_size);
  }, [formData.brand_name, formData.product_name, formData.volume_size]);

  // Full display name
  const displayName = useMemo(() => {
    return generateDisplayName(formData.brand_name, formData.product_name, formData.volume_size);
  }, [formData.brand_name, formData.product_name, formData.volume_size]);

  // Update sorting code automatically unless manually edited
  useEffect(() => {
    if (!manualCodeEdit && autoGeneratedCode) {
      setFormData(prev => ({ ...prev, sorting_code: autoGeneratedCode }));
    }
  }, [autoGeneratedCode, manualCodeEdit]);

  useEffect(() => {
    if (isEditing) {
      fetchProduct();
    }
  }, [id]);

  const fetchProduct = async () => {
    try {
      const response = await api.get(`/products/${id}`);
      const product = response.data.data;
      
      // Handle legacy products that might not have segmented fields
      const brandName = product.brand_name || '';
      const productName = product.product_name || '';
      const volumeSize = product.volume_size || '';
      const sortingCode = product.sorting_code || '';
      
      // If legacy product with only 'name' field, try to use it
      let legacyName = '';
      if (!brandName && !productName && product.name) {
        legacyName = product.name;
      }
      
      setFormData({
        brand_name: brandName || legacyName,
        product_name: productName,
        volume_size: volumeSize,
        sorting_code: sortingCode,
        description: product.description || '',
        cost_of_production: product.cost_of_production,
        markup_percentage: product.markup_percentage,
        markup_amount: product.markup_amount || '',
        stock_quantity: product.stock_quantity
      });
      
      // If there's an existing sorting code, assume it was manually set
      if (sortingCode) {
        setManualCodeEdit(true);
      }
    } catch (error) {
      console.error('Error fetching product:', error);
    }
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setPricingError('');
    
    // If user manually edits sorting code, mark it as manual
    if (name === 'sorting_code') {
      setManualCodeEdit(true);
    }
    
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const resetToAutoCode = () => {
    setManualCodeEdit(false);
    setFormData(prev => ({ ...prev, sorting_code: autoGeneratedCode }));
  };

  const copyCode = async () => {
    try {
      await navigator.clipboard.writeText(formData.sorting_code);
      setCodeCopied(true);
      setTimeout(() => setCodeCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  const addLineItem = () => {
    if (newLineItem.item_name && newLineItem.cost) {
      setLineItems([...lineItems, { ...newLineItem, id: Date.now() }]);
      setNewLineItem({ item_name: '', cost: '' });
    }
  };

  const removeLineItem = (itemId) => {
    setLineItems(lineItems.filter(item => item.id !== itemId));
  };

  const calculatedCoP = lineItems.reduce((sum, item) => sum + Number(item.cost || 0), 0);
  const finalCoP = lineItems.length > 0 ? calculatedCoP : Number(formData.cost_of_production || 0);
  const hasMarkupAmount = formData.markup_amount !== '' && formData.markup_amount !== null && formData.markup_amount !== undefined;
  const hasMarkupPercent = formData.markup_percentage !== '' && formData.markup_percentage !== null && formData.markup_percentage !== undefined;
  const appliedMarkup = hasMarkupAmount
    ? Number(formData.markup_amount || 0)
    : hasMarkupPercent
      ? (finalCoP * Number(formData.markup_percentage) / 100)
      : 0;
  const estimatedSP = finalCoP ? finalCoP + appliedMarkup : 0;
  const estimatedProfit = finalCoP ? estimatedSP - finalCoP : 0;

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    
    try {
      if (!hasMarkupAmount && !hasMarkupPercent) {
        setPricingError('Please provide either a markup percentage or a markup amount.');
        setLoading(false);
        return;
      }

      if (!formData.brand_name.trim()) {
        setPricingError('Brand name is required.');
        setLoading(false);
        return;
      }

      if (!formData.product_name.trim()) {
        setPricingError('Product name is required.');
        setLoading(false);
        return;
      }

      // Build the full product name for display
      const fullName = displayName;

      const productData = {
        // Segmented fields
        brand_name: formData.brand_name.trim(),
        product_name: formData.product_name.trim(),
        volume_size: formData.volume_size.trim(),
        sorting_code: formData.sorting_code.toUpperCase().trim(),
        // Combined display name
        name: fullName,
        description: formData.description,
        cost_of_production: lineItems.length > 0 ? calculatedCoP : formData.cost_of_production,
        markup_percentage: formData.markup_percentage,
        markup_amount: formData.markup_amount,
        stock_quantity: formData.stock_quantity
      };
      
      if (isEditing) {
        await api.put(`/products/${id}`, productData);
      } else {
        await api.post('/products', productData);
      }
      
      navigate('/inventory');
    } catch (error) {
      console.error('Error saving product:', error);
      alert('Error saving product. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  // ============ BULK MODE FUNCTIONS ============

  const addBulkProduct = () => {
    if (!newBulkProduct.product_name.trim()) {
      setPricingError('Product name is required.');
      return;
    }

    const sortingCode = generateSortingCode(bulkBrandName, newBulkProduct.product_name, newBulkProduct.volume_size);
    const fullName = generateDisplayName(bulkBrandName, newBulkProduct.product_name, newBulkProduct.volume_size);

    const productToAdd = {
      id: Date.now(),
      brand_name: bulkBrandName.trim(),
      product_name: newBulkProduct.product_name.trim(),
      volume_size: newBulkProduct.volume_size.trim(),
      sorting_code: sortingCode,
      name: fullName,
      description: newBulkProduct.description || '',
      // Use individual values or defaults
      cost_of_production: useDefaults ? bulkDefaults.cost_of_production : newBulkProduct.cost_of_production,
      markup_percentage: useDefaults ? bulkDefaults.markup_percentage : newBulkProduct.markup_percentage,
      markup_amount: useDefaults ? bulkDefaults.markup_amount : newBulkProduct.markup_amount,
      stock_quantity: useDefaults ? bulkDefaults.stock_quantity : newBulkProduct.stock_quantity
    };

    setBulkProducts([...bulkProducts, productToAdd]);
    setNewBulkProduct({
      product_name: '',
      volume_size: '',
      description: '',
      cost_of_production: '',
      markup_percentage: '',
      markup_amount: '',
      stock_quantity: ''
    });
    setPricingError('');
  };

  const removeBulkProduct = (productId) => {
    setBulkProducts(bulkProducts.filter(p => p.id !== productId));
  };

  const handleBulkSubmit = async () => {
    if (!bulkBrandName.trim()) {
      setPricingError('Brand name is required.');
      return;
    }

    if (bulkProducts.length === 0) {
      setPricingError('Add at least one product to the list.');
      return;
    }

    // Validate all products have required pricing
    for (const product of bulkProducts) {
      const hasMarkup = (product.markup_amount !== '' && product.markup_amount !== null) || 
                        (product.markup_percentage !== '' && product.markup_percentage !== null);
      if (!hasMarkup) {
        setPricingError(`Product "${product.product_name}" needs markup percentage or amount.`);
        return;
      }
      if (!product.cost_of_production && product.cost_of_production !== 0) {
        setPricingError(`Product "${product.product_name}" needs cost of production.`);
        return;
      }
    }

    setLoading(true);
    setPricingError('');

    try {
      // Add all products one by one
      for (const product of bulkProducts) {
        await api.post('/products', {
          brand_name: product.brand_name,
          product_name: product.product_name,
          volume_size: product.volume_size,
          sorting_code: product.sorting_code.toUpperCase(),
          name: product.name,
          description: product.description,
          cost_of_production: product.cost_of_production,
          markup_percentage: product.markup_percentage,
          markup_amount: product.markup_amount,
          stock_quantity: product.stock_quantity || 0
        });
      }

      navigate('/inventory');
    } catch (error) {
      console.error('Error saving products:', error);
      alert('Error saving products. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  // Calculate preview for bulk product being added
  const bulkNewProductCode = useMemo(() => {
    return generateSortingCode(bulkBrandName, newBulkProduct.product_name, newBulkProduct.volume_size);
  }, [bulkBrandName, newBulkProduct.product_name, newBulkProduct.volume_size]);

  return (
    <div className="add-product-page">
      <div className="add-product-header">
        <Link to="/inventory" className="back-link">
          <FiArrowLeft />
          <span>Back to Inventory</span>
        </Link>
      </div>

      <div className="add-product-container">
        <div className="add-product-main">
          <div className="page-title">
            <h1>{isEditing ? 'Edit Product' : 'Add New Product'}</h1>
            <p>Fill in the details below to {isEditing ? 'update' : 'create'} a product</p>
          </div>

          {/* Mode Toggle - Only show when not editing */}
          {!isEditing && (
            <div className="mode-toggle-card">
              <button 
                type="button"
                className={`mode-btn ${mode === 'single' ? 'active' : ''}`}
                onClick={() => setMode('single')}
              >
                <FiPackage size={18} />
                <span>Single Product</span>
              </button>
              <button 
                type="button"
                className={`mode-btn ${mode === 'bulk' ? 'active' : ''}`}
                onClick={() => setMode('bulk')}
              >
                <FiLayers size={18} />
                <span>Bulk Add</span>
              </button>
            </div>
          )}

          {/* ============ SINGLE MODE ============ */}
          {mode === 'single' && (
          <form onSubmit={handleSubmit}>
            {/* Product Identity Card */}
            <div className="form-card">
              <h3 className="section-title">
                <FiTag /> Product Identity
              </h3>
              <p className="section-description">
                Enter the brand and product details. The sorting code will be auto-generated.
              </p>
              
              <div className="form-row">
                <div className="form-group">
                  <label>Brand Name <span className="required">*</span></label>
                  <input 
                    type="text" 
                    name="brand_name" 
                    placeholder="e.g., Dr Vranjes" 
                    value={formData.brand_name} 
                    onChange={handleChange} 
                    required 
                  />
                  <small className="helper-text">The manufacturer or brand of the product</small>
                </div>

                <div className="form-group">
                  <label>Product Name <span className="required">*</span></label>
                  <input 
                    type="text" 
                    name="product_name" 
                    placeholder="e.g., Rosso Nobile Diffuser" 
                    value={formData.product_name} 
                    onChange={handleChange} 
                    required 
                  />
                  <small className="helper-text">The specific product name from this brand</small>
                </div>
              </div>

              <div className="form-row">
                <div className="form-group">
                  <label>Volume / Size</label>
                  <input 
                    type="text" 
                    name="volume_size" 
                    placeholder="e.g., 500ml, Large, 2L" 
                    value={formData.volume_size} 
                    onChange={handleChange} 
                  />
                  <small className="helper-text">The size, volume, or variant of the product</small>
                </div>

                <div className="form-group">
                  <label>
                    Sorting Code
                    {manualCodeEdit && (
                      <button 
                        type="button" 
                        className="btn-reset-code"
                        onClick={resetToAutoCode}
                        title="Reset to auto-generated code"
                      >
                        Reset
                      </button>
                    )}
                  </label>
                  <div className="sorting-code-input">
                    <input 
                      type="text" 
                      name="sorting_code" 
                      placeholder="Auto-generated" 
                      value={formData.sorting_code} 
                      onChange={handleChange}
                      className="code-input"
                      style={{ textTransform: 'uppercase', fontFamily: 'monospace', letterSpacing: '1px' }}
                    />
                    <button 
                      type="button" 
                      className="btn-copy-code"
                      onClick={copyCode}
                      title="Copy code"
                    >
                      {codeCopied ? <FiCheck /> : <FiCopy />}
                    </button>
                  </div>
                  <small className="helper-text">
                    {manualCodeEdit ? 'Manually edited' : 'Auto-generated from brand + product + volume'}
                  </small>
                </div>
              </div>

              {/* Preview of full product name */}
              {displayName && (
                <div className="name-preview">
                  <span className="preview-label">Full Product Name:</span>
                  <span className="preview-name">{displayName}</span>
                </div>
              )}
              
              <div className="form-group">
                <label>Description</label>
                <textarea 
                  name="description" 
                  placeholder="Additional notes or description" 
                  value={formData.description} 
                  onChange={handleChange}
                  rows="2"
                />
              </div>
            </div>

            <div className="form-card">
              <h3 className="section-title">
                <FiPackage /> Cost of Production
              </h3>
              <p className="section-description">
                Add materials/ingredients used to make this product. The total will be your Cost of Production.
              </p>

              {lineItems.length > 0 && (
                <div className="line-items-list">
                  {lineItems.map((item) => (
                    <div key={item.id} className="line-item">
                      <div className="line-item-content">
                        <span className="line-item-name">{item.item_name}</span>
                        <span className="line-item-cost">{formatCurrency(item.cost)}</span>
                      </div>
                      <button 
                        type="button"
                        onClick={() => removeLineItem(item.id)}
                        className="btn-remove"
                      >
                        <FiX />
                      </button>
                    </div>
                  ))}
                  <div className="line-items-total">
                    <span>Total CoP:</span>
                    <span className="total-amount">{formatCurrency(calculatedCoP)}</span>
                  </div>
                </div>
              )}

              <div className="add-line-item-form">
                <input 
                  type="text" 
                  placeholder="Item/Material name" 
                  value={newLineItem.item_name}
                  onChange={(e) => setNewLineItem({ ...newLineItem, item_name: e.target.value })}
                  className="line-item-input"
                />
                <input 
                  type="number" 
                  placeholder="Cost" 
                  step="0.01"
                  value={newLineItem.cost}
                  onChange={(e) => setNewLineItem({ ...newLineItem, cost: e.target.value })}
                  className="line-item-cost-input"
                />
                <button 
                  type="button"
                  onClick={addLineItem}
                  className="btn-add-item"
                >
                  <FiPlus /> Add Item
                </button>
              </div>

              {lineItems.length === 0 && (
                <div className="form-group" style={{ marginTop: '1rem' }}>
                  <label>Or enter Cost of Production directly ({currencySymbol}) <span className="required">*</span></label>
                  <input 
                    type="number" 
                    name="cost_of_production" 
                    placeholder="0.00" 
                    step="0.01"
                    value={formData.cost_of_production} 
                    onChange={handleChange} 
                    required={lineItems.length === 0}
                  />
                </div>
              )}
            </div>

            <div className="form-card">
              <h3 className="section-title">Pricing & Stock</h3>
              
              <div className="form-row">
                <div className="form-group">
                  <label>Markup Percentage (%)</label>
                  <input 
                    type="number" 
                    name="markup_percentage" 
                    placeholder="e.g., 50" 
                    value={formData.markup_percentage} 
                    onChange={handleChange} 
                  />
                  <small className="helper-text">Use percentage or amount — one is required.</small>
                </div>

                <div className="form-group">
                  <label>Markup Amount ({currencySymbol})</label>
                  <input
                    type="number"
                    name="markup_amount"
                    placeholder="e.g., 1500"
                    step="0.01"
                    value={formData.markup_amount}
                    onChange={handleChange}
                  />
                </div>
                
                <div className="form-group">
                  <label>Stock Quantity <span className="required">*</span></label>
                  <input 
                    type="number" 
                    name="stock_quantity" 
                    placeholder="0" 
                    value={formData.stock_quantity} 
                    onChange={handleChange} 
                    required 
                  />
                </div>
              </div>

              {pricingError && (
                <div className="pricing-error">{pricingError}</div>
              )}
            </div>

            <div className="form-actions">
              <button 
                type="button" 
                className="btn-secondary" 
                onClick={() => navigate('/inventory')}
              >
                Cancel
              </button>
              <button 
                type="submit" 
                className="btn-primary"
                disabled={loading}
              >
                <FiSave /> {loading ? 'Saving...' : (isEditing ? 'Update Product' : 'Add Product')}
              </button>
            </div>
          </form>
          )}

          {/* ============ BULK MODE ============ */}
          {mode === 'bulk' && !isEditing && (
            <div className="bulk-mode">
              {/* Brand Name Card */}
              <div className="form-card">
                <h3 className="section-title">
                  <FiTag /> Brand
                </h3>
                <p className="section-description">
                  Set the brand name once. All products below will use this brand.
                </p>
                
                <div className="form-group">
                  <label>Brand Name <span className="required">*</span></label>
                  <input 
                    type="text" 
                    placeholder="e.g., Dr Vranjes" 
                    value={bulkBrandName} 
                    onChange={(e) => setBulkBrandName(e.target.value)}
                  />
                </div>
              </div>

              {/* Default Pricing Card */}
              <div className="form-card">
                <h3 className="section-title">
                  <FiPackage /> Default Pricing & Stock
                </h3>
                <p className="section-description">
                  Set default values that will apply to all products (can be overridden per product).
                </p>

                <label className="checkbox-label" style={{ marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '0.5rem', cursor: 'pointer' }}>
                  <input 
                    type="checkbox" 
                    checked={useDefaults} 
                    onChange={(e) => setUseDefaults(e.target.checked)}
                    style={{ width: '16px', height: '16px' }}
                  />
                  <span>Use these defaults for all products</span>
                </label>

                <div className="form-row">
                  <div className="form-group">
                    <label>Cost of Production ({currencySymbol})</label>
                    <input 
                      type="number" 
                      placeholder="0.00" 
                      step="0.01"
                      value={bulkDefaults.cost_of_production} 
                      onChange={(e) => setBulkDefaults({ ...bulkDefaults, cost_of_production: e.target.value })}
                    />
                  </div>
                  <div className="form-group">
                    <label>Markup %</label>
                    <input 
                      type="number" 
                      placeholder="e.g., 50" 
                      value={bulkDefaults.markup_percentage} 
                      onChange={(e) => setBulkDefaults({ ...bulkDefaults, markup_percentage: e.target.value })}
                    />
                  </div>
                  <div className="form-group">
                    <label>Or Markup Amount ({currencySymbol})</label>
                    <input 
                      type="number" 
                      placeholder="e.g., 1500" 
                      step="0.01"
                      value={bulkDefaults.markup_amount} 
                      onChange={(e) => setBulkDefaults({ ...bulkDefaults, markup_amount: e.target.value })}
                    />
                  </div>
                  <div className="form-group">
                    <label>Stock Qty</label>
                    <input 
                      type="number" 
                      placeholder="0" 
                      value={bulkDefaults.stock_quantity} 
                      onChange={(e) => setBulkDefaults({ ...bulkDefaults, stock_quantity: e.target.value })}
                    />
                  </div>
                </div>
              </div>

              {/* Add Product Card */}
              <div className="form-card">
                <h3 className="section-title">
                  <FiPlus /> Add Products
                </h3>
                <p className="section-description">
                  Add products one by one. They will all use the brand name above.
                </p>

                <div className="bulk-add-form">
                  <div className="form-row">
                    <div className="form-group">
                      <label>Product Name <span className="required">*</span></label>
                      <input 
                        type="text" 
                        placeholder="e.g., Rosso Nobile Diffuser" 
                        value={newBulkProduct.product_name}
                        onChange={(e) => setNewBulkProduct({ ...newBulkProduct, product_name: e.target.value })}
                      />
                    </div>
                    <div className="form-group">
                      <label>Volume / Size</label>
                      <input 
                        type="text" 
                        placeholder="e.g., 500ml" 
                        value={newBulkProduct.volume_size}
                        onChange={(e) => setNewBulkProduct({ ...newBulkProduct, volume_size: e.target.value })}
                      />
                    </div>
                    <div className="form-group" style={{ flex: '0 0 auto' }}>
                      <label>Code Preview</label>
                      <div className="code-preview-inline">
                        {bulkNewProductCode || '---'}
                      </div>
                    </div>
                  </div>

                  {!useDefaults && (
                    <div className="form-row" style={{ marginTop: '0.75rem' }}>
                      <div className="form-group">
                        <label>Cost ({currencySymbol})</label>
                        <input 
                          type="number" 
                          placeholder="0.00" 
                          step="0.01"
                          value={newBulkProduct.cost_of_production}
                          onChange={(e) => setNewBulkProduct({ ...newBulkProduct, cost_of_production: e.target.value })}
                        />
                      </div>
                      <div className="form-group">
                        <label>Markup %</label>
                        <input 
                          type="number" 
                          placeholder="50"
                          value={newBulkProduct.markup_percentage}
                          onChange={(e) => setNewBulkProduct({ ...newBulkProduct, markup_percentage: e.target.value })}
                        />
                      </div>
                      <div className="form-group">
                        <label>Or Amount ({currencySymbol})</label>
                        <input 
                          type="number" 
                          placeholder="1500" 
                          step="0.01"
                          value={newBulkProduct.markup_amount}
                          onChange={(e) => setNewBulkProduct({ ...newBulkProduct, markup_amount: e.target.value })}
                        />
                      </div>
                      <div className="form-group">
                        <label>Stock</label>
                        <input 
                          type="number" 
                          placeholder="0"
                          value={newBulkProduct.stock_quantity}
                          onChange={(e) => setNewBulkProduct({ ...newBulkProduct, stock_quantity: e.target.value })}
                        />
                      </div>
                    </div>
                  )}

                  <button 
                    type="button"
                    className="btn-add-to-list"
                    onClick={addBulkProduct}
                    disabled={!bulkBrandName.trim() || !newBulkProduct.product_name.trim()}
                  >
                    <FiPlus /> Add to List
                  </button>
                </div>
              </div>

              {/* Products List */}
              {bulkProducts.length > 0 && (
                <div className="form-card">
                  <h3 className="section-title">
                    <FiLayers /> Products to Add ({bulkProducts.length})
                  </h3>

                  <div className="bulk-products-list">
                    {bulkProducts.map((product, index) => (
                      <div key={product.id} className="bulk-product-item">
                        <div className="bulk-product-info">
                          <div className="bulk-product-main">
                            <span className="bulk-product-code">{product.sorting_code}</span>
                            <span className="bulk-product-name">{product.name}</span>
                          </div>
                          <div className="bulk-product-details">
                            <span>CoP: {formatCurrency(product.cost_of_production || 0)}</span>
                            <span>
                              Markup: {product.markup_amount ? formatCurrency(product.markup_amount) : `${product.markup_percentage || 0}%`}
                            </span>
                            <span>Stock: {product.stock_quantity || 0}</span>
                          </div>
                        </div>
                        <button 
                          type="button"
                          className="btn-remove-bulk"
                          onClick={() => removeBulkProduct(product.id)}
                        >
                          <FiTrash2 size={16} />
                        </button>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {pricingError && (
                <div className="pricing-error" style={{ marginBottom: '1rem' }}>{pricingError}</div>
              )}

              <div className="form-actions">
                <button 
                  type="button" 
                  className="btn-secondary" 
                  onClick={() => navigate('/inventory')}
                >
                  Cancel
                </button>
                <button 
                  type="button" 
                  className="btn-primary"
                  onClick={handleBulkSubmit}
                  disabled={loading || bulkProducts.length === 0}
                >
                  <FiSave /> {loading ? 'Saving...' : `Add ${bulkProducts.length} Product${bulkProducts.length !== 1 ? 's' : ''}`}
                </button>
              </div>
            </div>
          )}
        </div>

        {/* Sidebar - Only show in single mode */}
        {mode === 'single' && (
        <div className="add-product-sidebar">
          {/* Sorting Code Preview */}
          <div className="preview-card code-preview">
            <h3>Sorting Code</h3>
            <div className="code-display">
              {formData.sorting_code || '---'}
            </div>
            <div className="code-breakdown">
              <div className="breakdown-item">
                <span className="breakdown-label">Brand:</span>
                <span className="breakdown-value">
                  {formData.brand_name ? formData.brand_name.trim().split(/\s+/).slice(0, 2).map(w => w.charAt(0).toUpperCase()).join('') : '--'}
                </span>
              </div>
              <div className="breakdown-item">
                <span className="breakdown-label">Product:</span>
                <span className="breakdown-value">
                  {formData.product_name ? formData.product_name.trim().split(/\s+/).map(w => w.charAt(0).toUpperCase()).join('') : '--'}
                </span>
              </div>
              <div className="breakdown-item">
                <span className="breakdown-label">Size:</span>
                <span className="breakdown-value">
                  {formData.volume_size ? (() => {
                    const match = formData.volume_size.match(/\d+/);
                    if (!match) return '--';
                    const num = parseInt(match[0], 10);
                    return num >= 1000 ? match[0].slice(0, 2) : match[0].charAt(0);
                  })() : '--'}
                </span>
              </div>
            </div>
          </div>

          {/* Price Preview */}
          <div className="preview-card">
            <h3>Price Preview</h3>
            
            <div className="preview-item">
              <span>Cost of Production:</span>
              <span className="preview-value">{formatCurrency(finalCoP)}</span>
            </div>
            
            <div className="preview-item">
              <span>
                Markup {hasMarkupAmount ? '(Amount)' : `(${formData.markup_percentage || 0}%)`}:
              </span>
              <span className="preview-value">{formatCurrency(estimatedSP - finalCoP, { showSign: true })}</span>
            </div>
            
            <div className="preview-divider"></div>
            
            <div className="preview-item">
              <span>Sales Price:</span>
              <span className="preview-value primary">{formatCurrency(estimatedSP)}</span>
            </div>
            
            <div className="preview-item">
              <span>Profit per Unit:</span>
              <span className="preview-value success">{formatCurrency(estimatedProfit, { showSign: true })}</span>
            </div>
          </div>
        </div>
        )}

        {/* Sidebar for Bulk Mode */}
        {mode === 'bulk' && !isEditing && (
          <div className="add-product-sidebar">
            <div className="preview-card code-preview">
              <h3>Brand Initials</h3>
              <div className="code-display">
                {bulkBrandName ? bulkBrandName.trim().split(/\s+/).slice(0, 2).map(w => w.charAt(0).toUpperCase()).join('') : '??'}
              </div>
              <p style={{ margin: '0.75rem 0 0', fontSize: '0.8rem', color: 'var(--text-secondary)', textAlign: 'center' }}>
                All products will start with these letters
              </p>
            </div>

            <div className="preview-card">
              <h3>Summary</h3>
              <div className="preview-item">
                <span>Products to add:</span>
                <span className="preview-value">{bulkProducts.length}</span>
              </div>
              {bulkProducts.length > 0 && (
                <>
                  <div className="preview-divider"></div>
                  <div className="preview-item">
                    <span>Total Stock:</span>
                    <span className="preview-value">
                      {bulkProducts.reduce((sum, p) => sum + Number(p.stock_quantity || 0), 0)} units
                    </span>
                  </div>
                </>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default AddProduct;
